# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fd4daf3ce9325186e959f9aaec5ee5a8889d1116e91a0f224b33b8f65ab80bc8d095fff9cce707ff27c8323f1e2138f3a93694ba4d736ef7d03cf57318c0989

test:
  secret_key_base: 997c8661db99aba51229d7454fe0fedcb272c9c6f5a421d2f15534e40877e75e4fb11db6d869b11c3f5f45721d87707adf9574f6ec91f2a09c8a72c4493b9027

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
